server:
  port: 8092
  servlet:
    context-path: /university

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      maximum-pool-size: 2
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-ui
  main:
    allow-bean-definition-overriding: true
app:
    name: mcb-juice
    version: 1
    description: Recruitment task for Mcb

security:
  signing-key: qazXdr4563x
  security-realm: test

jwt:
  authorizedGrantTypes: password,authorization_code,refresh_token
  accessTokenValiditySeconds: 3600
  client-secret: 829221
  secret: mcb0oskaoks
  clientId: mcb
  refreshTokenValiditySeconds: 86400